### ISSUE TITLE
Printing error messages for type checking errors nested within other remote calls

### ISSUE THREAD

**Issue by pcmoritz** [amplab/ray#214]
Try the following:

Start the shell, and type
```python
A = da.zeros([100, 100])
a = ray.get(A)
a.objrefs[1,1] = ray.put(0)
B = ray.put(a)
da.dot(B, B)
```

This crashes the workers and the error messages are not as nice as in #209

**Comment by robertnishihara** [comment]
Another thing which is actually a bug is that the failed tasks are marked as "running_tasks" and not as "failed_tasks".
