### ISSUE TITLE
pickling of functions with custom module types in Ray.remote fails

### ISSUE THREAD

**Issue by Wapaul1** [amplab/ray#323]
Steps to reproduce:

Have custom module to import such as below:

```
import pandas as pd

class DDataFrame(object):
  def __init__(self, dataframe=None):
    if dataframe is not None:
      self.dd = dataframe

  def deserialize(self, primitives):
    self.dd = pd.read_json(primitives)

  def serialize(self):
    return self.dd.to_json()
```

After importing the module, declare a remote function with the class type as an argument:
```
@ray.remote([dataframe.DDataFrame], [int])
def f(x):
  return 42
```

This will fail with error message:
```
Traceback (most recent call last):
  File "/home/ubuntu/ray/scripts/default_worker.py", line 23, in <module>
    ray.worker.main_loop()
  File "/home/ubuntu/ray/lib/python/ray/worker.py", line 739, in main_loop
    (function, arg_types, return_types, module) = pickling.loads(command_args)
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named dataframe
terminate called without an active exception
```

**Comment by mehrdadn** [comment]
I think we assume external modules are present already. You'd have to `pip install` them first.

**Comment by pcmoritz** [comment]
@Wapaul1: I our case what @mehrdadn means here is that dataframe should be in the PYTHONPATH of the worker (it is defined by us), did you check that? In other words, "import dataframe" should work from a python interpreter that was started from the home directory say.

**Comment by robertnishihara** [comment]
Closing because this works now.

1. We currently modify the paths of the workers so that if you can import something from the driver, then you should be able to import it on the workers as well (assuming the Python files actually exist on the workers in the same locations)
2. We changed the way we serialize custom classes and dropped type information.

This can be done as follows:

In `dataframe.py`, define:

```python
import pandas as pd

class DDataFrame(object):
  def __init__(self, dataframe=None):
    if dataframe is not None:
      self.dd = dataframe
```

Then run

```python
import dataframe
import ray

ray.init(start_ray_local=True, num_workers=1)

ray.register_class(dataframe.DDataFrame)

@ray.remote
def f(x):
  return 42

ray.get(f.remote(dataframe.DDataFrame()))
```

**Comment by Kuurusch** [comment]
@robertnishihara Sorry that I ask this here, but I think I have a similar problem with ray 0.8.5. So I have an own module and the file is also on my remote node, but the project-folder on the remote-node has not the exact same path. I've tried to set the PYTHONPATH, but it didn't worked. What could be here the problem? It gives me the ModuleNotFoundError.

2020-05-19 11:00:43,979    WARNING worker.py:1090 -- Failed to unpickle the remote function 'readData.calculateWraper' with function ID 212468463ddc722d66cbc39b249c6d80b535b5c1. Traceback:
Traceback (most recent call last):
  File "/home/sia1/Dokumente/SolarProject/venv/lib/python3.6/site-packages/ray/function_manager.py", line 177, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
ModuleNotFoundError: No module named 'gpForecast'

Is there somehow an option to set the path of my modules/code on the remote node?

Update: ok I've figured out that the option `--temp-dir` in the command `ray start` on the remote node did the trick! I've set the path to the folder, where I've stored my own python-modules and scripts on the remote machine.

**Comment by robertnishihara** [comment]
@Kuurusch, I'm a little surprised because I don't think `--temp-dir` should change anything. I would suggest installing your Python module on each node so that it can be imported. You can also set the PYTHONPATH on each machine by running

```
PYTHONPATH=... ray start ...
```

on each machine.

**Comment by Kuurusch** [comment]
@robertnishihara Hm, ok. So I would write into PYTHONPATH, which is empty on the remote-machine by the way, the start-command for ray?
I'm working with pyCharm, maybe there are other environmental variables used?
