### ISSUE TITLE
Floating point printing of ray objects

### ISSUE THREAD

**Issue by pcmoritz** [amplab/ray#326]
This is super confusing for people who debug numerics code:

```
import numpy as np
import ray

ray.services.start_ray_local(num_workers=1)
a = np.array([1.2120349123432143214], dtype="float32")
b = ray.get(ray.put(a))
```

This gives
```
In [13]: a.sum()
Out[13]: 1.2120349

In [14]: b.sum()
Out[14]: NDArray(1.2120349407196045, dtype=float32)
```
but they are actually the same:
```
In [18]: a.sum() - b.sum() == 0.0
Out[18]: True
```

This will go away once we get rid of NDArray and the other wrappers and use weak references to figure out when objects can be deallocated safely.

**Comment by robertnishihara** [comment]
This was addressed by #407.
