### ISSUE TITLE
Memory on remote node increases

### ISSUE THREAD

**Issue by Kuurusch** [amplab/ray#448]
Hallo,

I've setup successfully a cluster (ray 0.8.5) with two machines and I calculate on it different models in parallel. I do this for different settings of my model in python several hundred times in a for-loop and initialize and shutdown each time ray to clear the memory. This procedure worked on the local machine perfectly but on the remote node the memory is constantly increasing each time I initialize ray new. How can I clear the memory remotly for the remote node?

I'm working on two computers with Ubuntu 18.04LTS

Many thanks for your help!

**Comment by Kuurusch** [comment]
@robertnishihara I would expect, that shutdown() behaves the same like on the local machine, but seems to be not the case. Why? Is this a bug?

So what works on the local machine but not on a cluster:

ray.init()
... 
ray.shutdown()

**Comment by robertnishihara** [comment]
How are you starting Ray? If you do `ray.init()` it only starts it on one machine. Are you running `ray start ...` on the different machines to start a Ray cluster?

**Comment by Kuurusch** [comment]
@robertnishihara Yea, I start on each machine Ray with `ray start ...` to create a cluster. Afterwards I start calculating my models with ray.init(ip-of-cluster-head) and it distributes the workers over the cluster. But the problem with this approach is, that I cant clear the memory on the remote nodes of the cluster after each run with ray.shutdown().

So when I then restart a new calculation with ray.init((ip-of-cluster-head), the memory increases until there is no memory anymore available on the remote nodes.

I would assume, that the behavior is the same, if I run Ray only locally or on a cluster, thought that this is the idea of Ray.

The reason of the increasing memory is, that the processes of the already finished workers are not closed in ray and the only possibility to achiev this was to call ray.shutdown() and reinitialize it with ray.init()

With finished workers I mean when ray.get(calculateWraper.remote(...)) returned the result and is not anymore needed in the current iteration.

**Comment by istoica** [comment]
Adding @stephanie-wang and @ericl.

**Comment by robertnishihara** [comment]
Migrating this to https://github.com/ray-project/ray/issues/8822.
